-- 코드를 입력하세요
# SELECT *, SUM(S.SALES) * B.PRICE
# FROM BOOK_SALES AS S
# JOIN BOOK AS B ON S.BOOK_ID = B.BOOK_ID
# JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
# WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
# GROUP BY A.AUTHOR_ID, B.CATEGORY
# ORDER BY A.AUTHOR_ID, B.CATEGORY DESC

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, T.CATEGORY, SUM(TOTAL) AS TOTAL_SALES
FROM (SELECT B.BOOK_ID, B.AUTHOR_ID, B.CATEGORY, SUM(S.SALES)*B.PRICE AS TOTAL
FROM BOOK_SALES AS S
JOIN BOOK AS B ON B.BOOK_ID = S.BOOK_ID AND S.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY B.BOOK_ID) AS T
JOIN AUTHOR AS A ON A.AUTHOR_ID = T.AUTHOR_ID
GROUP BY T.AUTHOR_ID, T.CATEGORY
ORDER BY T.AUTHOR_ID, T.CATEGORY DESC

# SELECT *, SUM(S.SALES), SUM(S.SALES) * B.PRICE AS TMP
# FROM BOOK_SALES AS S
# JOIN BOOK AS B ON S.BOOK_ID = B.BOOK_ID
# WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
# GROUP BY B.AUTHOR_ID, B.CATEGORY, B.BOOK_ID

# PRICE 제대로 계산하기
# SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES) * B.PRICE AS TOTAL_SALES
# FROM BOOK_SALES AS S
# JOIN BOOK AS B ON S.BOOK_ID = B.BOOK_ID
# JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
# WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
# GROUP BY B.AUTHOR_ID, B.CATEGORY
# ORDER BY B.AUTHOR_ID, B.CATEGORY DESC