# SELECT A.PARENT_ID, COUNT(A.PARENT_ID)
# FROM ECOLI_DATA AS A
# JOIN ECOLI_DATA AS B ON A.PARENT_ID = B.ID
# GROUP BY A.PARENT_ID


# SELECT *
# FROM ECOLI_DATA AS A
# LEFT OUTER JOIN ECOLI_DATA AS B ON B.PARENT_ID = A.ID

# SELECT *
# FROM ECOLI_DATA AS A
# LEFT OUTER JOIN ECOLI_DATA AS B ON B.PARENT_ID = A.ID

SELECT A.ID, COUNT(B.PARENT_ID) AS CHILD_COUNT
FROM ECOLI_DATA AS A
LEFT OUTER JOIN ECOLI_DATA AS B ON B.PARENT_ID = A.ID
GROUP BY A.ID
ORDER BY A.ID ASC