-- 코드를 입력하세요
# SELECT *
# FROM REST_INFO

SELECT J.FOOD_TYPE, J.REST_ID, J.REST_NAME, J.FAVORITES
FROM (SELECT FOOD_TYPE, MAX(FAVORITES) AS M
FROM REST_INFO
GROUP BY FOOD_TYPE) AS F
JOIN REST_INFO AS J ON J.FAVORITES = F.M AND J.FOOD_TYPE = F.FOOD_TYPE
ORDER BY FOOD_TYPE DESC