-- 코드를 작성해주세요
WITH RABKEDDATA AS (
    SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS RANK_SIZE 
    FROM ECOLI_DATA
)

SELECT E.ID, 
CASE WHEN RANK_SIZE = 1 THEN 'CRITICAL'
     WHEN RANK_SIZE = 2 THEN 'HIGH'
     WHEN RANK_SIZE = 3 THEN 'MEDIUM'
     ELSE 'LOW'
END AS COLONY_NAME

FROM ECOLI_DATA E
JOIN RABKEDDATA R ON E.ID = R.ID

ORDER BY E.ID;
