WITH RECURSIVE cte as (
    SELECT ID, PARENT_ID, 1 as depth
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL

    SELECT e.ID, e.PARENT_ID, cte.depth+1
    FROM ECOLI_DATA as e
    JOIN cte ON e.PARENT_ID = cte.ID
)
SELECT count(*) as COUNT, depth as GENERATION
FROM cte
WHERE ID NOT IN (
    SELECT PARENT_ID 
    FROM ECOLI_DATA 
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION;