-- 코드를 작성해주세요
SELECT ROUTE, CONCAT(T,'km') AS TOTAL_DISTANCE, CONCAT(AV, 'km') AS AVERAGE_DISTANCE
FROM (SELECT ROUTE, ROUND(SUM(D_BETWEEN_DIST),1) AS T, ROUND(AVG(D_BETWEEN_DIST),2) AS AV
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY T DESC) AS A