-- 코드를 작성해주세요

SELECT COUNT(A.FISH_NAME) AS FISH_COUNT, A.FISH_NAME
FROM (SELECT FISH_NAME
FROM FISH_INFO AS F
JOIN FISH_NAME_INFO AS N ON F.FISH_TYPE = N.FISH_TYPE) AS A
GROUP BY A.FISH_NAME
ORDER BY FISH_COUNT DESC