# SELECT CAR_ID,
#     CASE 
#         WHEN END_DATE <= '2022-10-16' THEN '대여 가능'
#         ELSE '대여중'
#         END AS AVAILABILITY
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# ORDER BY CAR_ID DESC


# SELECT CAR_ID,
#     CASE 
#         WHEN START_DATE <= '2022-10-16' AND END_DATE > '2022-10-16' THEN '대여중'
#         ELSE '대여가능'
#         END AS AVAILABILITY,
#     START_DATE, END_DATE
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# # WHERE START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16'
# GROUP BY CAR_ID, AVAILABILITY
# ORDER BY CAR_ID DESC



# SELECT CAR_ID, START_DATE, END_DATE
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE CAR_ID IN (28,29,30)
# ORDER BY CAR_ID DESC

# SELECT CAR_ID,
# CASE 
#     WHEN CAR_ID IN (SELECT CAR_ID
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY CAR_ID
# HAVING MAX(START_DATE) < '2022-10-16' AND MAX(END_DATE) >= '2022-10-16') THEN '대여중'
#     ELSE '대여가능'
#     END AS AVAILABILITY
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# ORDER BY CAR_ID DESC

# SELECT CAR_ID
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY CAR_ID
# ORDER BY CAR_ID DESC

SELECT CAR_ID,
    CASE
        WHEN MAX(
            CASE
                WHEN START_DATE <= '2022-10-16'
                AND END_DATE >= '2022-10-16'
                THEN 1
                ELSE 0
            END
        ) = 1
        THEN '대여중'
        ELSE '대여 가능'
        END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC