-- 코드를 입력하세요
SELECT o.PRODUCT_ID, p.PRODUCT_NAME, SUM(p.PRICE * o.AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER o
JOIN FOOD_PRODUCT p ON o.PRODUCT_ID = p.PRODUCT_ID
WHERE YEAR(o.PRODUCE_DATE) = 2022 AND MONTH(o.PRODUCE_DATE) = 5
GROUP BY o.PRODUCT_ID, p.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, o.PRODUCT_ID ASC;