WITH TOTAL AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_CNT
    FROM (
        SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF
        UNION ALL
        SELECT FLAVOR, TOTAL_ORDER FROM JULY
    ) AS MERGED
    GROUP BY FLAVOR
),
RANKED AS (
    SELECT
        FLAVOR,
        TOTAL_CNT,
        RANK() OVER (ORDER BY TOTAL_CNT DESC) AS rk
    FROM TOTAL
)
SELECT FLAVOR
FROM RANKED
WHERE rk <= 3 
ORDER BY TOTAL_CNT DESC;
