-- 코드를 입력하세요
SELECT U.WRITER_ID AS USER_ID, UU.NICKNAME, SUM(U.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS U
JOIN USED_GOODS_USER AS UU ON U.WRITER_ID = UU.USER_ID
WHERE STATUS = 'DONE'
GROUP BY USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES