WITH ONE_P AS (
    SELECT M.MEMBER_NAME, R.REVIEW_TEXT, R.REVIEW_DATE, COUNT(*) AS CNT
    FROM REST_REVIEW R
    JOIN MEMBER_PROFILE M ON R.MEMBER_ID = M.MEMBER_ID
    GROUP BY R.MEMBER_ID
    ORDER BY CNT DESC
    LIMIT 1
)

SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW R
JOIN MEMBER_PROFILE M ON R.MEMBER_ID = M.MEMBER_ID
JOIN ONE_P OP ON OP.MEMBER_NAME = M.MEMBER_NAME
ORDER BY REVIEW_DATE ASC, R.REVIEW_TEXT ASC;
