-- 코드를 작성해주세요

SELECT YEAR, J.MAXSIZE - SIZE_OF_COLONY AS YEAR_DEV, E.ID
FROM ECOLI_DATA AS E
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR , MAX(SIZE_OF_COLONY) AS MAXSIZE
 FROM ECOLI_DATA
 GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS J ON YEAR(E.DIFFERENTIATION_DATE) = J.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC