SELECT FLAVOR
FROM(
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_CNT
    FROM (
        SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF
        UNION ALL
        SELECT FLAVOR, TOTAL_ORDER FROM JULY
    ) AS MERGED
    GROUP BY FLAVOR
    ORDER BY TOTAL_CNT DESC
    LIMIT 3) as t;