-- 코드를 작성해주세요
SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM (SELECT ID,A.FISH_TYPE,A.LENGTH
FROM (SELECT FISH_TYPE , MAX(LENGTH) AS LENGTH
FROM FISH_INFO
GROUP BY FISH_TYPE) AS A
JOIN FISH_INFO AS B ON A.FISH_TYPE = B.FISH_TYPE AND A.LENGTH = B.LENGTH) AS A
JOIN FISH_NAME_INFO AS B ON A.FISH_TYPE = B.FISH_TYPE


