-- 코드를 작성해주세요

# SELECT FISH_TYPE, AVG(LENGTH) AS LEN
# FROM (SELECT FISH_TYPE, IFNULL(LENGTH,10) FROM FISH_INFO)
# GROUP BY FISH_TYPE
# HAVING LEN>33

SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(IFNULL(LENGTH, 10)) > 33
ORDER BY FISH_TYPE