-- 코드를 작성해주세요

# SELECT FISH_TYPE, AVG(LENGTH) AS LEN
# FROM (SELECT FISH_TYPE, IFNULL(LENGTH,10) FROM FISH_INFO)
# GROUP BY FISH_TYPE
# HAVING LEN>33

SELECT B.FISH_COUNT, B.MAX_LENGTH, B.FISH_TYPE
FROM (SELECT FISH_TYPE, AVG(IFNULL(LENGTH,10)) AS A, COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING A > 33) AS B
ORDER BY FISH_TYPE